version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./aic-aspnet-core-linux-demo.sln && dotnet publish ./aic-aspnet-core-linux-demo.sln -c Release -o ./obj/Docker/publish"
